export const TYPES = {
  LOADING_MOVIES: 'LOADING_MOVIES',
  GET_DISCOVER_MOVIES: 'GET_DISCOVER_MOVIES',
  GET_TOP_RATED: 'GET_TOP_RATED',
  GET_CREDITS_MOVIES: 'GET_CREDITS',

  SET_THEME: 'SET_THEME',
};
